### ISSUE TITLE
The target setting doesn't seem to work

### ISSUE THREAD

**Issue by kainam00** [CenterForAssessment/atom-gist-dev#4]
It defaults to /tmp regardless of what is set in the target directory box. 

OSX 10.10.4
Atom 1.0.3

**Comment by bclinkinbeard** [comment]
Yea, I think I have an issue logged for this already. There are permissions issues with other locations and I haven't had time to troubleshoot yet.

**Comment by bclinkinbeard** [comment]
Duplicate of #1
